/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-29 14:03:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BoardMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>portfolio_list</title>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <link rel = \"stylesheet\" type = \"text/css\" href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/BoardMain.css\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/Board_Search_Form.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/Board_SideMenu.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"pfcontainer\">\r\n");
      out.write("        <div class=\"boardroute\"><h4 id=\"boardroute\">포트폴리오 > 웹개발자</h4></div>\r\n");
      out.write("        <div class=\"pftitle\">\r\n");
      out.write("            <h3 id=\"portfoliotitle\">포트폴리오</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pfsort\">\r\n");
      out.write("            <select id=\"pfsort\" name=\"pfsort\">\r\n");
      out.write("                <option name=\"sort\" value=\"최신순\">최신순</option>\r\n");
      out.write("                <option name=\"sort\" value=\"경력\">경력</option>\r\n");
      out.write("                <option name=\"sort\" value=\"언어\">언어</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pfboardcontents\">\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pfcontents\">\r\n");
      out.write("                <div id=\"pfthumbnail\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/freeboard/developer.png\" style=\"width:95%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pftitle\"><h4>portfoliotitle</h4></div>\r\n");
      out.write("                <div id=\"pfviews\"><h6>조회수</h6></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pfpaging\">\r\n");
      out.write("            <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                <ul class=\"pagination justify-content-center\">\r\n");
      out.write("                  <li class=\"page-item disabled\">\r\n");
      out.write("                    <a class=\"page-link\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">&laquo;</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                  <li class=\"page-item\">\r\n");
      out.write("                    <a class=\"page-link\" href=\"#\">&raquo;</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"finclude\">\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
